### ISSUE TITLE
Firefox Crashing

### ISSUE THREAD

**Issue by capriciousduck** [accetto/ubuntu-vnc-xfce#11]
Firefox is crashing. How to fix? Does passing --shm-size fix the issue?

**Comment by accetto** [comment]
I assume, that you've used this image as a base and then you've installed Firefox yourself. If this is the case, then you definitely have to increase the shared memory size to at least 256MB. You can check [this page in Wiki](https://github.com/accetto/xubuntu-vnc/wiki/Firefox-multiprocess) for more information.

**Comment by capriciousduck** [comment]
Okay. I got it fixed. But why isn't snap working(installed snapd)? I am not able to install apps from the snapstore. Doesn't snap work  in a xfce docker environment?

**Comment by accetto** [comment]
Good question. I've also found that it's not working, but I had no time to investigate it further then. Actually, snap hasn't convinced me yet, even outside containers. Currently I'm preparing new generation of containers based on Ubuntu 20.04 LTS, but they will also not include snap. At least not yet, because I'm trying to keep reasonable image sizes, which is not the case you get by default. Would you have time to investigate the snap case?

**Comment by capriciousduck** [comment]
No. I lack the skills. I know Python and basic bash skills. That's it.

**Comment by capriciousduck** [comment]
Can you implement this( https://github.com/ogra1/snapd-docker ) into your docker image?

**Comment by capriciousduck** [comment]
I've got firefox to work using shm size parameter. How do I install chrome? Downloading the google-chrome deb and installing got no errors. But the browser is not starting if the --no-sandbox parameter is not passed.
